# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WorldGridSquares
                                 A QGIS plugin
 世界メッシュ試行版です。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-13
        copyright            : (C) 2026 by Research Institute for World Grid Squares
        email                : kametarou3000@outlook.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WorldGridSquares class from file WorldGridSquares.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .world_grid_squares import WorldGridSquares
    return WorldGridSquares(iface)
