# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WorldGridSquares
                                 A QGIS plugin
 世界メッシュ試行版です。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-13
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Research Institute for World Grid Squares
        email                : kametarou3000@outlook.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .world_grid_squares_dialog import WorldGridSquaresDialog
import os.path

# 追加のライブラリ
from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsProject,
    QgsPointXY,
    QgsApplication,
    QgsVectorLayer,
    QgsFeature,
    QgsGeometry,
    QgsFields,
    QgsField,
    QgsFillSymbol,
    QgsPalLayerSettings,
    QgsVectorLayerSimpleLabeling,
    QgsTextFormat
)
from qgis.PyQt.QtGui import QColor, QFont
from PyQt5.QtGui import QColor
from PyQt5.QtCore import QVariant
from .lib.latitude_and_longitude import LatitudeAndLongitude
from .lib.mesh_code import MeshCode
from .lib.coordinate import Coordinate

# from qgis.core import QgsProject


class WorldGridSquares:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'WorldGridSquares_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&World Grid Squares')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('WorldGridSquares', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/world_grid_squares/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'世界メッシュの試行版です。'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&World Grid Squares'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = WorldGridSquaresDialog()

        # mesh数のカウント
        self.dlg.pushButton.clicked.connect(self.count_meshes)

        # メッシュの表示（OKボタン）
        self.dlg.button_box.accepted.connect(self.draw_meshes)


        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

        # 緯度経度を返す。

    def get_latitudeandlongitude(self):
        # 現在のキャンバスの表示範囲（地図座標系）
        extent = self.iface.mapCanvas().extent()

        ######################################################
        print("CRS:", self.iface.activeLayer().crs().authid())
        ######################################################

        # EPSG:3857 -> EPSG:4326

        # 現在のプロジェクトの CRS（例: EPSG:qgis ラスタレイヤ 画面表示されている四隅の緯度経度をpythonで求める方法3857 など）
        src_crs = self.iface.mapCanvas().mapSettings().destinationCrs()

        # 緯度経度（EPSG:4326）に変換するための CRS
        dest_crs = QgsCoordinateReferenceSystem("EPSG:4326")

        # 座標変換オブジェクトを作成
        transform = QgsCoordinateTransform(src_crs, dest_crs, QgsProject.instance())

        # 四隅の座標を変換
        top_left = transform.transform(extent.xMinimum(), extent.yMaximum())
        top_right = transform.transform(extent.xMaximum(), extent.yMaximum())
        bottom_left = transform.transform(extent.xMinimum(), extent.yMinimum())
        bottom_right = transform.transform(extent.xMaximum(), extent.yMinimum())

        return {"top_left": [top_left.y(), top_left.x()],
                "top_right": [top_right.y(), top_right.x()],
                "bottom_left": [bottom_left.y(), bottom_left.x()],
                "bottom_right": [bottom_right.y(), bottom_right.x()]}


    def get_code(self, mesh_size):
        coordinate = self.get_latitudeandlongitude()

        top_left_code = LatitudeAndLongitude(coordinate["top_left"][0], coordinate["top_left"][1])
        top_right_code = LatitudeAndLongitude(coordinate["top_right"][0], coordinate["top_right"][1])
        bottom_left_code = LatitudeAndLongitude(coordinate["bottom_left"][0], coordinate["bottom_left"][1])
        bottom_right_code = LatitudeAndLongitude(coordinate["bottom_right"][0], coordinate["bottom_right"][1])

        if mesh_size == "1km":
            top_left_code = top_left_code.wgs_code_1km()
            top_right_code = top_right_code.wgs_code_1km()
            bottom_left_code = bottom_left_code.wgs_code_1km()
            bottom_right_code = bottom_right_code.wgs_code_1km()
        elif mesh_size == "500m":
            top_left_code = top_left_code.wgs_code_500m()
            top_right_code = top_right_code.wgs_code_500m()
            bottom_left_code = bottom_left_code.wgs_code_500m()
            bottom_right_code = bottom_right_code.wgs_code_500m()
        elif mesh_size == "250m":
            top_left_code = top_left_code.wgs_code_250m()
            top_right_code = top_right_code.wgs_code_250m()
            bottom_left_code = bottom_left_code.wgs_code_250m()
            bottom_right_code = bottom_right_code.wgs_code_250m()
        elif mesh_size == "125m":
            top_left_code = top_left_code.wgs_code_125m()
            top_right_code = top_right_code.wgs_code_125m()
            bottom_left_code = bottom_left_code.wgs_code_125m()
            bottom_right_code = bottom_right_code.wgs_code_125m()
        elif mesh_size == "100m":
            top_left_code = top_left_code.wgs_code_100m()
            top_right_code = top_right_code.wgs_code_100m()
            bottom_left_code = bottom_left_code.wgs_code_100m()
            bottom_right_code = bottom_right_code.wgs_code_100m()
        elif mesh_size == "10m":
            top_left_code = top_left_code.wgs_code_10m()
            top_right_code = top_right_code.wgs_code_10m()
            bottom_left_code = bottom_left_code.wgs_code_10m()
            bottom_right_code = bottom_right_code.wgs_code_10m()
        elif mesh_size == "1m":
            top_left_code = top_left_code.wgs_code_1m()
            top_right_code = top_right_code.wgs_code_1m()
            bottom_left_code = bottom_left_code.wgs_code_1m()
            bottom_right_code = bottom_right_code.wgs_code_1m()

        return {"top_left_code": top_left_code, "top_right_code": top_right_code,
                "bottom_left_code": bottom_left_code, "bottom_right_code": bottom_right_code}

    def get_coordinate(self, codes_in_area, mesh_size):
        top_left_meshcode = MeshCode(codes_in_area["top_left_code"])
        top_right_meshcode = MeshCode(codes_in_area["top_right_code"])
        bottom_left_meshcode = MeshCode(codes_in_area["bottom_left_code"])
        bottom_right_meshcode = MeshCode(codes_in_area["bottom_right_code"])

        if mesh_size == "1km":
            top_left_coordinate = top_left_meshcode.coordinate_1km()
            top_right_coordinate = top_right_meshcode.coordinate_1km()
            bottom_left_coordinate = bottom_left_meshcode.coordinate_1km()
            bottom_right_coordinate = bottom_right_meshcode.coordinate_1km()
        elif mesh_size == "500m":
            top_left_coordinate = top_left_meshcode.coordinate_500m()
            top_right_coordinate = top_right_meshcode.coordinate_500m()
            bottom_left_coordinate = bottom_left_meshcode.coordinate_500m()
            bottom_right_coordinate = bottom_right_meshcode.coordinate_500m()
        elif mesh_size == "250m":
            top_left_coordinate = top_left_meshcode.coordinate_250m()
            top_right_coordinate = top_right_meshcode.coordinate_250m()
            bottom_left_coordinate = bottom_left_meshcode.coordinate_250m()
            bottom_right_coordinate = bottom_right_meshcode.coordinate_250m()
        elif mesh_size == "125m":
            top_left_coordinate = top_left_meshcode.coordinate_125m()
            top_right_coordinate = top_right_meshcode.coordinate_125m()
            bottom_left_coordinate = bottom_left_meshcode.coordinate_125m()
            bottom_right_coordinate = bottom_right_meshcode.coordinate_125m()
        elif mesh_size == "100m":
            top_left_coordinate = top_left_meshcode.coordinate_100m()
            top_right_coordinate = top_right_meshcode.coordinate_100m()
            bottom_left_coordinate = bottom_left_meshcode.coordinate_100m()
            bottom_right_coordinate = bottom_right_meshcode.coordinate_100m()
        elif mesh_size == "10m":
            top_left_coordinate = top_left_meshcode.coordinate_10m()
            top_right_coordinate = top_right_meshcode.coordinate_10m()
            bottom_left_coordinate = bottom_left_meshcode.coordinate_10m()
            bottom_right_coordinate = bottom_right_meshcode.coordinate_10m()
        elif mesh_size == "1m":
            top_left_coordinate = top_left_meshcode.coordinate_1m()
            top_right_coordinate = top_right_meshcode.coordinate_1m()
            bottom_left_coordinate = bottom_left_meshcode.coordinate_1m()
            bottom_right_coordinate = bottom_right_meshcode.coordinate_1m()

        return {"top_left_coordinate": top_left_coordinate, "top_right_coordinate": top_right_coordinate,
                "bottom_left_coordinate": bottom_left_coordinate, "bottom_right_coordinate": bottom_right_coordinate}

    def count_meshes(self):
        # comboboxの値を取得
        mesh_size = self.dlg.comboBox.currentText()
        codes_in_area = self.get_code(mesh_size)

        coordinates_in_area = self.get_coordinate(codes_in_area, mesh_size)
        x_length = int(coordinates_in_area["bottom_right_coordinate"]["x"]) \
                   - int(coordinates_in_area["bottom_left_coordinate"]["x"]) + 1
        y_length = int(coordinates_in_area["top_left_coordinate"]["y"]) \
                   - int(coordinates_in_area["bottom_left_coordinate"]["y"]) + 1
        mesh_number = x_length * y_length

        # mesh_numberをsetTextする。
        self.dlg.textEdit.setText(str(mesh_number))

    def get_meshes(self, area_coordinates, mesh_size):
        area_meshes = []
        for combi in area_coordinates:
            coordinate = Coordinate(combi[0], combi[1])
            if mesh_size == "1km":
                area_meshes.append(coordinate.wgs_code_1km())
            elif mesh_size == "500m":
                area_meshes.append(coordinate.wgs_code_500m())
            elif mesh_size == "250m":
                area_meshes.append(coordinate.wgs_code_250m())
            elif mesh_size == "125m":
                area_meshes.append(coordinate.wgs_code_125m())
            elif mesh_size == "100m":
                area_meshes.append(coordinate.wgs_code_100m())
            elif mesh_size == "10m":
                area_meshes.append(coordinate.wgs_code_10m())
            elif mesh_size == "1m":
                area_meshes.append(coordinate.wgs_code_10m())

        return area_meshes


    def get_news(self, meshes, mesh_size):
        list_meshes = []
        for mesh in meshes:
            meshcode = MeshCode(mesh)
            if mesh_size == "1km":
                news = meshcode.wgs_1km_news()
            elif mesh_size == "500m":
                news = meshcode.wgs_500m_news()
            elif mesh_size == "250m":
                news = meshcode.wgs_250m_news()
            elif mesh_size == "125m":
                news = meshcode.wgs_125m_news()
            elif mesh_size == "100m":
                news = meshcode.wgs_100m_news()
            elif mesh_size == "10m":
                news = meshcode.wgs_10m_news()
            elif mesh_size == "1m":
                news = meshcode.wgs_1m_news()

            list_meshes.append({"meshcode": mesh, "news":news})

        return list_meshes


    def show_data(self, mydata, layer_name):

        layer_bs = self.iface.activeLayer()
        crs_id = layer_bs.crs().authid()
        dest_crs = QgsCoordinateReferenceSystem(crs_id)

        layer = QgsVectorLayer('Polygon', layer_name, 'memory')
        pr = layer.dataProvider()

        # new fieldの追加
        new_fields = [QgsField("メッシュコード", QVariant.String), QgsField("面積(km2)", QVariant.String),
                      QgsField("緯度距離（北側）(m)", QVariant.String),
                      QgsField("緯度距離（南側）(m)", QVariant.String),
                      QgsField("経度距離(m)", QVariant.String)]
        pr.addAttributes(new_fields)
        layer.updateFields()

        for row in mydata:

            # polygon追加
            poly = QgsFeature()
            geom = QgsGeometry.fromWkt(row["WKT"])
            poly.setGeometry(geom)

            # new fieldに
            poly.setAttributes([row["meshcode"],
                                round(row["area"]/1000000,2),
                                round(row["latitude_North"],2),
                                round(row["latitude_South"],2),
                                round(row["longitude"],2)])

            # new featureを追加
            pr.addFeatures([poly])

        layer.updateExtents()

        # 現在のシンボルを取得
        symbol = layer.renderer().symbol()

        # 塗りつぶし色を取得
        current_color = symbol.color()

        # 新しい色（透明度を下げる）
        # QColor(R, G, B, Alpha)  Alpha=0〜255
        new_color = QColor(current_color.red(),
                           current_color.green(),
                           current_color.blue(),
                           100)  # 100 は半透明

        # 色を設定
        symbol.setColor(new_color)

        # レイヤーを再描画
        layer.triggerRepaint()



        QgsProject.instance().addMapLayers([layer])

        pass



    def draw_meshes(self):
        # comboboxの値を取得
        mesh_size = self.dlg.comboBox.currentText()
        codes_in_area = self.get_code(mesh_size)
        coordinates_in_area = self.get_coordinate(codes_in_area, mesh_size)
        area_coordinates = Coordinate.get_area_news(x_min=int(coordinates_in_area["bottom_left_coordinate"]["x"]),
                                                    x_max=int(coordinates_in_area["bottom_right_coordinate"]["x"]),
                                                    y_min=int(coordinates_in_area["bottom_left_coordinate"]["y"]),
                                                    y_max=int(coordinates_in_area["top_left_coordinate"]["y"]))
        area_meshes = self.get_meshes(area_coordinates, mesh_size)
        mesh_news = self.get_news(area_meshes, mesh_size)

        mylist = []
        for item in mesh_news:
            wkt = LatitudeAndLongitude.dict2wkt(North=item["news"]["North"], South=item["news"]["South"],
                                                East=item["news"]["East"], West=item["news"]["West"])
            distance_latitude_North = LatitudeAndLongitude.distance(latitude_a=item["news"]["North"],
                                                                    longitude_a=item["news"]["West"],
                                                                    latitude_b=item["news"]["North"],
                                                                    longitude_b=item["news"]["East"])
            distance_latitude_South = LatitudeAndLongitude.distance(latitude_a=item["news"]["South"],
                                                                    longitude_a=item["news"]["West"],
                                                                    latitude_b=item["news"]["South"],
                                                                    longitude_b=item["news"]["East"])
            longitude = LatitudeAndLongitude.distance(latitude_a=item["news"]["North"],
                                                                    longitude_a=item["news"]["East"],
                                                                    latitude_b=item["news"]["South"],
                                                                    longitude_b=item["news"]["East"])
            area = LatitudeAndLongitude.rectangle_area(latitude_a=item["news"]["North"],
                                                       longitude_a=item["news"]["East"],
                                                       latitude_b=item["news"]["North"],
                                                       longitude_b=item["news"]["West"],
                                                       latitude_c=item["news"]["South"],
                                                       longitude_c=item["news"]["West"],
                                                       latitude_d=item["news"]["South"],
                                                       longitude_d=item["news"]["East"])
            mylist.append({"meshcode":item["meshcode"],
                           "WKT": wkt,
                           "area":area,
                           "latitude_North":distance_latitude_North,
                           "latitude_South":distance_latitude_South,
                           "longitude":longitude})

        self.show_data(mylist, mesh_size)





