# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WorldGridSquaresDialog
                                 A QGIS plugin
 世界メッシュ試行版です。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-13
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Research Institute for World Grid Squares
        email                : kametarou3000@outlook.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'world_grid_squares_dialog_base.ui'))


class WorldGridSquaresDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(WorldGridSquaresDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # comboBoxの選択肢
        self.comboBox.addItems(['1km', '500m', '250m', '125m', '100m', '10m', '1m'])

    def accept(self):
        pass
